name: format-check

on:
  push:
    branches:
      - "master"
      - "release-"
    tags: "*"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - uses: actions/checkout@v4
      - name: Install JuliaFormatter and format
        shell: julia --color=yes {0}
        run: |
          using Pkg
          # This will use the latest version by default but you can set the version like so:
          # Pkg.add(name="JuliaFormatter", version="0.13.0")
          Pkg.add("JuliaFormatter")
          using JuliaFormatter
          format(".", verbose=true)
      - name: Format check
        shell: julia --color=yes {0}
        run: |
          out = Cmd(`git diff`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files have not been formatted !!!"
              write(stdout, out)
              exit(1)
          end
